// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvNEI-ptLnkU9QiDSfW70P954ZrzYSmQA',
    appId: '1:50182814659:web:7f1a4403a9b259026e1b76',
    messagingSenderId: '50182814659',
    projectId: 'smartlabtest-71fa7',
    authDomain: 'smartlabtest-71fa7.firebaseapp.com',
    databaseURL: 'https://smartlabtest-71fa7-default-rtdb.firebaseio.com',
    storageBucket: 'smartlabtest-71fa7.appspot.com',
    measurementId: 'G-VJDN580WM7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC63dbwgAA7Eb2_5UkWdrreygeBODgfmE',
    appId: '1:50182814659:android:439cb861ea019aad6e1b76',
    messagingSenderId: '50182814659',
    projectId: 'smartlabtest-71fa7',
    databaseURL: 'https://smartlabtest-71fa7-default-rtdb.firebaseio.com',
    storageBucket: 'smartlabtest-71fa7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgGns55HXvZHp5astEjdFkjP1TggIQLL0',
    appId: '1:50182814659:ios:723f2a4c82e7d5576e1b76',
    messagingSenderId: '50182814659',
    projectId: 'smartlabtest-71fa7',
    databaseURL: 'https://smartlabtest-71fa7-default-rtdb.firebaseio.com',
    storageBucket: 'smartlabtest-71fa7.appspot.com',
    iosClientId: '50182814659-0uqkq3a0e0cio9ce43iu1980h8m5n2sl.apps.googleusercontent.com',
    iosBundleId: 'com.example.hardwarehubtest',
  );
}
